### ISSUE TITLE
PIDCommand needs a wrapper in order to operate properly

### ISSUE THREAD

**Issue by BrenekH** [BrenekH/kotlin-for-frc-i#35]

**Comment by zPaw** [comment]
A java wrapper may not be required. Intellij Java to Kotlin conversion is setting up DoubleSuppliers, BiConsumers, etc. to handle the PID commands and subsystems. So that's probably the way to go instead of an entire java file

**Comment by BrenekH** [comment]
Fixed because of the previously mentioned Kotlin "convenience" feature for casting to the required types.
